name: runtime-params

runtimeParameterDefinitions:
- fieldName: LLM_DEPLOYMENT_ID
  type: deployment

- fieldName: db_credential
  type: credential

- fieldName: SNOWFLAKE_ACCOUNT
  type: string

- fieldName: SNOWFLAKE_WAREHOUSE
  type: string

- fieldName: SNOWFLAKE_DATABASE
  type: string

- fieldName: SNOWFLAKE_SCHEMA
  type: string

- fieldName: SNOWFLAKE_ROLE
  type: string
